//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediinfo.WinForm.ExpressionCustomControl {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpressionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpressionResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mediinfo.WinForm.ExpressionCustomControl.ExpressionResource", typeof(ExpressionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abs(Value)
        ///Returns the absolute, positive value of the given numeric expression. 的本地化字符串。
        /// </summary>
        internal static string AbsDescription {
            get {
                return ResourceManager.GetString("AbsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acos(Value)
        ///Returns the arccosine of a number (the angle, in radians, whose cosine is the given float expression). 的本地化字符串。
        /// </summary>
        internal static string AcosDescription {
            get {
                return ResourceManager.GetString("AcosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddDays(DateTime, DaysCount)
        ///Returns a date-time value that is the specified number of days away from the specified DateTime. 的本地化字符串。
        /// </summary>
        internal static string AddDaysDescription {
            get {
                return ResourceManager.GetString("AddDaysDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddHours(DateTime, HoursCount)
        ///Returns a date-time value that is the specified number of hours away from the specified DateTime. 的本地化字符串。
        /// </summary>
        internal static string AddHoursDescription {
            get {
                return ResourceManager.GetString("AddHoursDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddMilliSeconds(DateTime, MilliSecondsCount)
        ///Returns a date-time value that is the specified number of milliseconds away from the specified DateTime. 的本地化字符串。
        /// </summary>
        internal static string AddMilliSecondsDescription {
            get {
                return ResourceManager.GetString("AddMilliSecondsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddMinutes(DateTime, MinutesCount)
        ///Returns a date-time value that is the specified number of minutes away from the specified DateTime. 的本地化字符串。
        /// </summary>
        internal static string AddMinutesDescription {
            get {
                return ResourceManager.GetString("AddMinutesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddMonths(DateTime, MonthsCount)
        ///Returns a date-time value that is the specified number of months away from the specified DateTime. 的本地化字符串。
        /// </summary>
        internal static string AddMonthsDescription {
            get {
                return ResourceManager.GetString("AddMonthsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddSeconds(DateTime, SecondsCount)
        ///Returns a date-time value that is the specified number of seconds away from the specified DateTime. 的本地化字符串。
        /// </summary>
        internal static string AddSecondsDescription {
            get {
                return ResourceManager.GetString("AddSecondsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTicks(DateTime, TicksCount)
        ///Returns a date-time value that is the specified number of ticks away from the specified DateTime. 的本地化字符串。
        /// </summary>
        internal static string AddTicksDescription {
            get {
                return ResourceManager.GetString("AddTicksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTimeSpan(DateTime, TimeSpan)
        ///Returns a date-time value that is away from the specified DateTime for the given TimeSpan. 的本地化字符串。
        /// </summary>
        internal static string AddTimeSpanDescription {
            get {
                return ResourceManager.GetString("AddTimeSpanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddYears(DateTime, YearsCount)
        ///Returns a date-time value that is the specified number of years away from the specieid DateTime. 的本地化字符串。
        /// </summary>
        internal static string AddYearsDescription {
            get {
                return ResourceManager.GetString("AddYearsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performs a logical conjunction on two expressions. 的本地化字符串。
        /// </summary>
        internal static string AndDescription {
            get {
                return ResourceManager.GetString("AndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ascii(String)
        ///Returns the ASCII code value of the leftmost character in a character expression. 的本地化字符串。
        /// </summary>
        internal static string AsciiDescription {
            get {
                return ResourceManager.GetString("AsciiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asin(Value)
        ///Returns the arcsine of a number (the angle, in radians, whose sine is the given float expression). 的本地化字符串。
        /// </summary>
        internal static string AsinDescription {
            get {
                return ResourceManager.GetString("AsinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Atn2(Value1, Value2)
        ///Returns the angle whose tangent is the quotient of two specified numbers, in radians. 的本地化字符串。
        /// </summary>
        internal static string Atn2Description {
            get {
                return ResourceManager.GetString("Atn2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Atn(Value)
        ///Returns the arctangent of a number (the angle, in radians, whose tangent is the given float expression). 的本地化字符串。
        /// </summary>
        internal static string AtnDescription {
            get {
                return ResourceManager.GetString("AtnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avg(Value)
        ///Evaluates the average of the values in the collection. 的本地化字符串。
        /// </summary>
        internal static string AvgAggregateDescription {
            get {
                return ResourceManager.GetString("AvgAggregateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色表达式 的本地化字符串。
        /// </summary>
        internal static string BCRGBDescription {
            get {
                return ResourceManager.GetString("BCRGBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Between (,)
        ///Specifies a range to test. Returns true if a value is greater than or equal to the first operand and less than or equal to the second operand. 的本地化字符串。
        /// </summary>
        internal static string BetweenDescription {
            get {
                return ResourceManager.GetString("BetweenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BigMul(Value1, Value2)
        ///Returns an Int64 containing the full product of two specified 32-bit numbers. 的本地化字符串。
        /// </summary>
        internal static string BigMulDescription {
            get {
                return ResourceManager.GetString("BigMulDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performs a bitwise logical AND operation between two integer values. 的本地化字符串。
        /// </summary>
        internal static string BitwiseAndDescription {
            get {
                return ResourceManager.GetString("BitwiseAndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compares each bit of its first operand to the corresponding bit of its second operand. If either bit is 1, the corresponding result bit is set to 1. Otherwise, the corresponding result bit is set to 0. 的本地化字符串。
        /// </summary>
        internal static string BitwiseOrDescription {
            get {
                return ResourceManager.GetString("BitwiseOrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performs a logical exclusion on two Boolean expressions, or a bitwise exclusion on two numeric expressions. 的本地化字符串。
        /// </summary>
        internal static string BitwiseXorDescription {
            get {
                return ResourceManager.GetString("BitwiseXorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string buttonCancelText {
            get {
                return ResourceManager.GetString("buttonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string buttonOKText {
            get {
                return ResourceManager.GetString("buttonOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ceiling(Value)
        ///Returns the smallest integer that is greater than or equal to the given numeric expression. 的本地化字符串。
        /// </summary>
        internal static string CeilingDescription {
            get {
                return ResourceManager.GetString("CeilingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Char(Number)
        ///Converts an integerASCIICode to a character. 的本地化字符串。
        /// </summary>
        internal static string CharDescription {
            get {
                return ResourceManager.GetString("CharDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CharIndex(String1, String2, StartLocation)
        ///Returns the starting position of String1 within String2, beginning from the StartLocation character position to the end of a string. 的本地化字符串。
        /// </summary>
        internal static string CharIndex3ParamDescription {
            get {
                return ResourceManager.GetString("CharIndex3ParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CharIndex(String1, String2)
        ///Returns the starting position of String1 within String2, beginning from the zero character position to the end of a string. 的本地化字符串。
        /// </summary>
        internal static string CharIndexDescription {
            get {
                return ResourceManager.GetString("CharIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列名称 的本地化字符串。
        /// </summary>
        internal static string ColumnText {
            get {
                return ResourceManager.GetString("ColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concat(String1, ... , StringN)
        ///Returns a string value containing the concatenation of the current string with any additional strings. 的本地化字符串。
        /// </summary>
        internal static string ConcatDescription {
            get {
                return ResourceManager.GetString("ConcatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition expression editor 的本地化字符串。
        /// </summary>
        internal static string ConditionCaption {
            get {
                return ResourceManager.GetString("ConditionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition Editor 的本地化字符串。
        /// </summary>
        internal static string ConditionText {
            get {
                return ResourceManager.GetString("ConditionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常量 的本地化字符串。
        /// </summary>
        internal static string ConstantsText {
            get {
                return ResourceManager.GetString("ConstantsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains(String, SubString)
        ///Returns True if SubString occurs within String; otherwise, False is returned. 的本地化字符串。
        /// </summary>
        internal static string ContainsDescription {
            get {
                return ResourceManager.GetString("ContainsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cos(Value)
        ///Returns the cosine of the angle defined in radians. 的本地化字符串。
        /// </summary>
        internal static string CosDescription {
            get {
                return ResourceManager.GetString("CosDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cosh(Value)
        ///Returns the hyperbolic cosine of the angle defined in radians. 的本地化字符串。
        /// </summary>
        internal static string CoshDescription {
            get {
                return ResourceManager.GetString("CoshDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count()
        ///Returns the number of objects in a collection. 的本地化字符串。
        /// </summary>
        internal static string CountAggregateDescription {
            get {
                return ResourceManager.GetString("CountAggregateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the index of the current data row in a datasource. Note that this index is zero-based. 的本地化字符串。
        /// </summary>
        internal static string CurrentRowIndexDescription {
            get {
                return ResourceManager.GetString("CurrentRowIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateDiffDay(startDate, endDate)
        ///Returns the number of day boundaries between two non-nullable dates. 的本地化字符串。
        /// </summary>
        internal static string DateDiffDayDescription {
            get {
                return ResourceManager.GetString("DateDiffDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateDiffHour(startDate, endDate)
        ///Returns the number of hour boundaries between two non-nullable dates. 的本地化字符串。
        /// </summary>
        internal static string DateDiffHourDescription {
            get {
                return ResourceManager.GetString("DateDiffHourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateDiffMilliSecond(startDate, endDate)
        ///Returns the number of millisecond boundaries between two non-nullable dates. 的本地化字符串。
        /// </summary>
        internal static string DateDiffMilliSecondDescription {
            get {
                return ResourceManager.GetString("DateDiffMilliSecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateDiffMinute(startDate, endDate)
        ///Returns the number of minute boundaries between two non-nullable dates. 的本地化字符串。
        /// </summary>
        internal static string DateDiffMinuteDescription {
            get {
                return ResourceManager.GetString("DateDiffMinuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateDiffMonth(startDate, endDate)
        ///Returns the number of month boundaries between two non-nullable dates. 的本地化字符串。
        /// </summary>
        internal static string DateDiffMonthDescription {
            get {
                return ResourceManager.GetString("DateDiffMonthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateDiffSecond(startDate, endDate)
        ///Returns the number of second boundaries between two non-nullable dates. 的本地化字符串。
        /// </summary>
        internal static string DateDiffSecondDescription {
            get {
                return ResourceManager.GetString("DateDiffSecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateDiffTick(startDate, endDate)
        ///Returns the number of tick boundaries between two non-nullable dates. 的本地化字符串。
        /// </summary>
        internal static string DateDiffTickDescription {
            get {
                return ResourceManager.GetString("DateDiffTickDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateDiffYear(startDate, endDate)
        ///Returns the number of year boundaries between two non-nullable dates. 的本地化字符串。
        /// </summary>
        internal static string DateDiffYearDescription {
            get {
                return ResourceManager.GetString("DateDiffYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Divides the first operand by the second. 的本地化字符串。
        /// </summary>
        internal static string DivideDescription {
            get {
                return ResourceManager.GetString("DivideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件状态表达式 的本地化字符串。
        /// </summary>
        internal static string EnableDescription {
            get {
                return ResourceManager.GetString("EnableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndsWith(String, EndString)
        ///Returns True if the end of String matches EndString; otherwise, False is returned. 的本地化字符串。
        /// </summary>
        internal static string EndsWithDescription {
            get {
                return ResourceManager.GetString("EndsWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns true if both operands have the same value; otherwise, it returns false. 的本地化字符串。
        /// </summary>
        internal static string EqualDescription {
            get {
                return ResourceManager.GetString("EqualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exists()
        ///Determines whether the object exists in the collection. 的本地化字符串。
        /// </summary>
        internal static string ExistsAggregateDescription {
            get {
                return ResourceManager.GetString("ExistsAggregateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp(Value)
        ///Returns the exponential value of the given float expression. 的本地化字符串。
        /// </summary>
        internal static string ExpDescription {
            get {
                return ResourceManager.GetString("ExpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression Editor 的本地化字符串。
        /// </summary>
        internal static string ExpressionText {
            get {
                return ResourceManager.GetString("ExpressionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Represents the Boolean False value. 的本地化字符串。
        /// </summary>
        internal static string FalseDescription {
            get {
                return ResourceManager.GetString("FalseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of this field is:  的本地化字符串。
        /// </summary>
        internal static string FieldsDescriptionPrefix {
            get {
                return ResourceManager.GetString("FieldsDescriptionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fields 的本地化字符串。
        /// </summary>
        internal static string FieldsText {
            get {
                return ResourceManager.GetString("FieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Floor(Value)
        ///Returns the largest integer less than or equal to the given numeric expression. 的本地化字符串。
        /// </summary>
        internal static string FloorDescription {
            get {
                return ResourceManager.GetString("FloorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体表达式 的本地化字符串。
        /// </summary>
        internal static string FontDescription {
            get {
                return ResourceManager.GetString("FontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format rule expression editor 的本地化字符串。
        /// </summary>
        internal static string FormatRuleCaption {
            get {
                return ResourceManager.GetString("FormatRuleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数 的本地化字符串。
        /// </summary>
        internal static string FunctionsText {
            get {
                return ResourceManager.GetString("FunctionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aggregate 的本地化字符串。
        /// </summary>
        internal static string functionsTypesPropertiesAggregateItems {
            get {
                return ResourceManager.GetString("functionsTypesPropertiesAggregateItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (All) 的本地化字符串。
        /// </summary>
        internal static string functionsTypesPropertiesAllItems {
            get {
                return ResourceManager.GetString("functionsTypesPropertiesAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date-time 的本地化字符串。
        /// </summary>
        internal static string functionsTypesPropertiesDateTimeItems {
            get {
                return ResourceManager.GetString("functionsTypesPropertiesDateTimeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logical 的本地化字符串。
        /// </summary>
        internal static string functionsTypesPropertiesLogicalItems {
            get {
                return ResourceManager.GetString("functionsTypesPropertiesLogicalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Math 的本地化字符串。
        /// </summary>
        internal static string functionsTypesPropertiesMathItems {
            get {
                return ResourceManager.GetString("functionsTypesPropertiesMathItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String 的本地化字符串。
        /// </summary>
        internal static string functionsTypesPropertiesStringItems {
            get {
                return ResourceManager.GetString("functionsTypesPropertiesStringItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetDate(DateTime)
        ///Extracts a date from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetDateDescription {
            get {
                return ResourceManager.GetString("GetDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetDay(DateTime)
        ///Extracts a day from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetDayDescription {
            get {
                return ResourceManager.GetString("GetDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetDayOfWeek(DateTime)
        ///Extracts a day of the week from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetDayOfWeekDescription {
            get {
                return ResourceManager.GetString("GetDayOfWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetDayOfYear(DateTime)
        ///Extracts a day of the year from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetDayOfYearDescription {
            get {
                return ResourceManager.GetString("GetDayOfYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetHour(DateTime)
        ///Extracts an hour from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetHourDescription {
            get {
                return ResourceManager.GetString("GetHourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetMilliSecond(DateTime)
        ///Extracts milliseconds from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetMilliSecondDescription {
            get {
                return ResourceManager.GetString("GetMilliSecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetMinute(DateTime)
        ///Extracts minutes from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetMinuteDescription {
            get {
                return ResourceManager.GetString("GetMinuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetMonth(DateTime)
        ///Extracts a month from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetMonthDescription {
            get {
                return ResourceManager.GetString("GetMonthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetSecond(DateTime)
        ///Extracts seconds from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetSecondDescription {
            get {
                return ResourceManager.GetString("GetSecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetTimeOfDay(DateTime)
        ///Extracts the time of the day from the defined DateTime, in ticks. 的本地化字符串。
        /// </summary>
        internal static string GetTimeOfDayDescription {
            get {
                return ResourceManager.GetString("GetTimeOfDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetYear(DateTime)
        ///Extracts a year from the defined DateTime. 的本地化字符串。
        /// </summary>
        internal static string GetYearDescription {
            get {
                return ResourceManager.GetString("GetYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greater than operator. Used to compare expressions. 的本地化字符串。
        /// </summary>
        internal static string GreaterDescription {
            get {
                return ResourceManager.GetString("GreaterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greater than or equal to operator. Used to compare expressions. 的本地化字符串。
        /// </summary>
        internal static string GreaterOrEqualDescription {
            get {
                return ResourceManager.GetString("GreaterOrEqualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Information
        ///Caption: {1}
        ///The type of this field is: {2} 的本地化字符串。
        /// </summary>
        internal static string GridFieldsDescriptionPrefix {
            get {
                return ResourceManager.GetString("GridFieldsDescriptionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Iif(Expression, TruePart, FalsePart)
        ///Returns either TruePart or FalsePart, depending on the evaluation of the Boolean Expression. 的本地化字符串。
        /// </summary>
        internal static string IifDescription {
            get {
                return ResourceManager.GetString("IifDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In (,,,)
        ///Tests for the existence of a property in an object. 的本地化字符串。
        /// </summary>
        internal static string InDescription {
            get {
                return ResourceManager.GetString("InDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert(String1, StartPosition, String2)
        ///Inserts String2 into String1 at the position specified by StartPositon 的本地化字符串。
        /// </summary>
        internal static string InsertDescription {
            get {
                return ResourceManager.GetString("InsertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsNull(Value)
        ///Returns True if the specified Value is NULL. 的本地化字符串。
        /// </summary>
        internal static string IsNullDescription {
            get {
                return ResourceManager.GetString("IsNullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsNullOrEmpty(String)
        ///Returns True if the specified String object is NULL or an empty string; otherwise, False is returned. 的本地化字符串。
        /// </summary>
        internal static string IsNullOrEmptyDescription {
            get {
                return ResourceManager.GetString("IsNullOrEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsThisMonth(DateTime)
        ///Returns True if the specified date falls within the current month. 的本地化字符串。
        /// </summary>
        internal static string IsThisMonthDescription {
            get {
                return ResourceManager.GetString("IsThisMonthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsThisWeek(DateTime)
        ///Returns True if the specified date falls within the current week. 的本地化字符串。
        /// </summary>
        internal static string IsThisWeekDescription {
            get {
                return ResourceManager.GetString("IsThisWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsThisYear(DateTime)
        ///Returns True if the specified date falls within the current year. 的本地化字符串。
        /// </summary>
        internal static string IsThisYearDescription {
            get {
                return ResourceManager.GetString("IsThisYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Len(Value)
        ///Returns an integer containing either the number of characters in a string or the nominal number of bytes required to store a variable. 的本地化字符串。
        /// </summary>
        internal static string LenDescription {
            get {
                return ResourceManager.GetString("LenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Less than operator. Used to compare expressions. 的本地化字符串。
        /// </summary>
        internal static string LessDescription {
            get {
                return ResourceManager.GetString("LessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Less than or equal to operator. Used to compare expressions. 的本地化字符串。
        /// </summary>
        internal static string LessOrEqualDescription {
            get {
                return ResourceManager.GetString("LessOrEqualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compares a string against a pattern. If the value of the string matches the pattern, result is true. If the string does not match the pattern, result is false. If both string and pattern are empty strings, the result is true. 的本地化字符串。
        /// </summary>
        internal static string LikeDescription {
            get {
                return ResourceManager.GetString("LikeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeDayAfterTomorrow()
        ///Returns a date-time value corresponding to the day after Tomorrow. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeDayAfterTomorrowDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeDayAfterTomorrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeLastWeek()
        ///Returns a date-time value corresponding to the first day of the previous week. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeLastWeekDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeLastWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeNextMonth()
        ///Returns a date-time value corresponding to the first day of next month. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeNextMonthDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeNextMonthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeNextWeek()
        ///Returns a date-time value corresponding to the first day of the following week. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeNextWeekDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeNextWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeNextYear()
        ///Returns a date-time value corresponding to the first day of the following year. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeNextYearDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeNextYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeNow()
        ///Returns a date-time value corresponding to the current moment in time. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeNowDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeNowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeThisMonth()
        ///Returns a date-time value corresponding to the first day of the current month. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeThisMonthDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeThisMonthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeThisWeek()
        ///Returns a date-time value corresponding to the first day of the current week. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeThisWeekDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeThisWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeThisYear()
        ///Returns a date-time value corresponding to the first day of the current year. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeThisYearDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeThisYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeToday()
        ///Returns a date-time value corresponding to Today. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeTodayDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeTodayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeTomorrow()
        ///Returns a date-time value corresponding to Tomorrow. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeTomorrowDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeTomorrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeTwoWeeksAway()
        ///Returns a date-time value corresponding to the first day of the week that is after next week. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeTwoWeeksAwayDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeTwoWeeksAwayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalDateTimeYesterday()
        ///Returns a date-time value corresponding to Yesterday. 的本地化字符串。
        /// </summary>
        internal static string LocalDateTimeYesterdayDescription {
            get {
                return ResourceManager.GetString("LocalDateTimeYesterdayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log10(Value)
        ///Returns the base 10 logarithm of a specified number. 的本地化字符串。
        /// </summary>
        internal static string Log10Description {
            get {
                return ResourceManager.GetString("Log10Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log(Value, Base)
        ///Returns the logarithm of a specified number in a specified Base. 的本地化字符串。
        /// </summary>
        internal static string Log2ParamDescription {
            get {
                return ResourceManager.GetString("Log2ParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log(Value)
        ///Returns the natural logarithm of a specified number. 的本地化字符串。
        /// </summary>
        internal static string LogDescription {
            get {
                return ResourceManager.GetString("LogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lower(String)
        ///Returns the String in lowercase. 的本地化字符串。
        /// </summary>
        internal static string LowerDescription {
            get {
                return ResourceManager.GetString("LowerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max(Value)
        ///Returns the maximum expression value in a collection. 的本地化字符串。
        /// </summary>
        internal static string MaxAggregateDescription {
            get {
                return ResourceManager.GetString("MaxAggregateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max(Value1, Value2)
        ///Returns the maximum value from the specified values. 的本地化字符串。
        /// </summary>
        internal static string MaxDescription {
            get {
                return ResourceManager.GetString("MaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min(Value)
        ///Returns the minimum expression value in a collection. 的本地化字符串。
        /// </summary>
        internal static string MinAggregateDescription {
            get {
                return ResourceManager.GetString("MinAggregateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min(Value1, Value2)
        ///Returns the minimum value from the specified values. 的本地化字符串。
        /// </summary>
        internal static string MinDescription {
            get {
                return ResourceManager.GetString("MinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finds the difference between two numbers. 的本地化字符串。
        /// </summary>
        internal static string MinusDescription {
            get {
                return ResourceManager.GetString("MinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the remainder (modulus) obtained by dividing one numeric expression into another. 的本地化字符串。
        /// </summary>
        internal static string ModuloDescription {
            get {
                return ResourceManager.GetString("ModuloDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiplies the value of two expressions. 的本地化字符串。
        /// </summary>
        internal static string MultiplyDescription {
            get {
                return ResourceManager.GetString("MultiplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非空表达式 的本地化字符串。
        /// </summary>
        internal static string NoneEmptyDescription {
            get {
                return ResourceManager.GetString("NoneEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performs logical negation on an expression. 的本地化字符串。
        /// </summary>
        internal static string NotDescription {
            get {
                return ResourceManager.GetString("NotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns true if the operands do not have the same value; otherwise, it returns false. 的本地化字符串。
        /// </summary>
        internal static string NotEqualDescription {
            get {
                return ResourceManager.GetString("NotEqualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now()
        ///Returns the current system date and time. 的本地化字符串。
        /// </summary>
        internal static string NowDescription {
            get {
                return ResourceManager.GetString("NowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Represents a null reference, one that does not refer to any object. 的本地化字符串。
        /// </summary>
        internal static string NullDescription {
            get {
                return ResourceManager.GetString("NullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运算操作符 的本地化字符串。
        /// </summary>
        internal static string OperatorsText {
            get {
                return ResourceManager.GetString("OperatorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performs a logical disjunction on two Boolean expressions. 的本地化字符串。
        /// </summary>
        internal static string OrDescription {
            get {
                return ResourceManager.GetString("OrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PadLeft(String, Length, Char)
        ///Left-aligns characters in the defined string, padding its left side with the specified Char up to a specified total length. 的本地化字符串。
        /// </summary>
        internal static string PadLeft3ParamDescription {
            get {
                return ResourceManager.GetString("PadLeft3ParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PadLeft(String, Length)
        ///Left-aligns characters in the defined string, padding its left side with white space characters up to a specified total length. 的本地化字符串。
        /// </summary>
        internal static string PadLeftDescription {
            get {
                return ResourceManager.GetString("PadLeftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PadRight(String, Length, Char)
        ///Right-aligns characters in the defined string, padding its left side with the specified Char up to a specified total length. 的本地化字符串。
        /// </summary>
        internal static string PadRight3ParamDescription {
            get {
                return ResourceManager.GetString("PadRight3ParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PadRight(String, Length)
        ///Right-aligns characters in the defined string, padding its left side with white space characters up to a specified total length. 的本地化字符串。
        /// </summary>
        internal static string PadRightDescription {
            get {
                return ResourceManager.GetString("PadRightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of this parameter is:  的本地化字符串。
        /// </summary>
        internal static string ParametersDescriptionPrefix {
            get {
                return ResourceManager.GetString("ParametersDescriptionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        internal static string ParametersText {
            get {
                return ResourceManager.GetString("ParametersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds the value of one numeric expression to another, or concatenates two strings. 的本地化字符串。
        /// </summary>
        internal static string PlusDescription {
            get {
                return ResourceManager.GetString("PlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power(Value, Power)
        ///Returns a specified number raised to a specified power. 的本地化字符串。
        /// </summary>
        internal static string PowerDescription {
            get {
                return ResourceManager.GetString("PowerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove(String, StartPosition)
        ///Deletes all characters from this instance, beginning at a specified position. 的本地化字符串。
        /// </summary>
        internal static string Remove2ParamDescription {
            get {
                return ResourceManager.GetString("Remove2ParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove(String, StartPosition, Length)
        ///Deletes a specified number of characters from this instance, beginning at a specified position. 的本地化字符串。
        /// </summary>
        internal static string Remove3ParamDescription {
            get {
                return ResourceManager.GetString("Remove3ParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace(String, SubString2, String3)
        ///Returns a copy of String1, in which SubString2 has been replaced with String3. 的本地化字符串。
        /// </summary>
        internal static string ReplaceDescription {
            get {
                return ResourceManager.GetString("ReplaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse(String)
        ///Reverses the order of elements within a string. 的本地化字符串。
        /// </summary>
        internal static string ReverseDescription {
            get {
                return ResourceManager.GetString("ReverseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前景色表达式 的本地化字符串。
        /// </summary>
        internal static string RGBDescription {
            get {
                return ResourceManager.GetString("RGBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rnd()
        ///Returns a random number that is less than 1, but greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string RndDescription {
            get {
                return ResourceManager.GetString("RndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Round(Value, Precision)
        ///Rounds the given value to the nearest integer, or to a specified number of decimal places. 的本地化字符串。
        /// </summary>
        internal static string Round2ParamDescription {
            get {
                return ResourceManager.GetString("Round2ParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Round(Value)
        ///Rounds the given value to the nearest integer. 的本地化字符串。
        /// </summary>
        internal static string RoundDescription {
            get {
                return ResourceManager.GetString("RoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the total amount of data rows in a datasource. 的本地化字符串。
        /// </summary>
        internal static string RowCountDescription {
            get {
                return ResourceManager.GetString("RowCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign(Value)
        ///Returns the positive (+1), zero (0), or negative (-1) sign of the given expression. 的本地化字符串。
        /// </summary>
        internal static string SignDescription {
            get {
                return ResourceManager.GetString("SignDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sin(Value)
        ///Returns the sine of the angle, defined in radians. 的本地化字符串。
        /// </summary>
        internal static string SinDescription {
            get {
                return ResourceManager.GetString("SinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single()
        ///Returns a single object from the collection. 的本地化字符串。
        /// </summary>
        internal static string SingleAggregateDescription {
            get {
                return ResourceManager.GetString("SingleAggregateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sinh(Value)
        ///Returns the hyperbolic sine of the angle defined in radians. 的本地化字符串。
        /// </summary>
        internal static string SinhDescription {
            get {
                return ResourceManager.GetString("SinhDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sqr(Value)
        ///Returns the square root of a given number. 的本地化字符串。
        /// </summary>
        internal static string SqrDescription {
            get {
                return ResourceManager.GetString("SqrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartsWith(String, StartString)
        ///Returns True if the beginning of String matches StartString; otherwise, False is returned. 的本地化字符串。
        /// </summary>
        internal static string StartsWithDescription {
            get {
                return ResourceManager.GetString("StartsWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Substring(String, StartPosition)
        ///Retrieves a substring from String. The substring starts at StartPosition. 的本地化字符串。
        /// </summary>
        internal static string Substring2paramDescription {
            get {
                return ResourceManager.GetString("Substring2paramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Substring(String, StartPosition, Length)
        ///Retrieves a substring from String. The substring starts at StartPosition and has the specified Length. 的本地化字符串。
        /// </summary>
        internal static string Substring3paramDescription {
            get {
                return ResourceManager.GetString("Substring3paramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum(Value)
        ///Returns the sum of all the expression values in the collection. 的本地化字符串。
        /// </summary>
        internal static string SumAggregateDescription {
            get {
                return ResourceManager.GetString("SumAggregateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tan(Value)
        ///Returns the tangent of the angle defined in radians. 的本地化字符串。
        /// </summary>
        internal static string TanDescription {
            get {
                return ResourceManager.GetString("TanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tanh(Value)
        ///Returns the hyperbolic tangent of the angle defined in radians. 的本地化字符串。
        /// </summary>
        internal static string TanhDescription {
            get {
                return ResourceManager.GetString("TanhDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today()
        ///Returns the current date. Regardless of the actual time, this function returns midnight of the current date. 的本地化字符串。
        /// </summary>
        internal static string TodayDescription {
            get {
                return ResourceManager.GetString("TodayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToDecimal(Value)
        ///Converts Value to an equivalent decimal number. 的本地化字符串。
        /// </summary>
        internal static string ToDecimalDescription {
            get {
                return ResourceManager.GetString("ToDecimalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToDouble(Value)
        ///Converts Value to an equivalent 64-bit double-precision floating-point number. 的本地化字符串。
        /// </summary>
        internal static string ToDoubleDescription {
            get {
                return ResourceManager.GetString("ToDoubleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToFloat(Value)
        ///Converts Value to an equivalent 32-bit single-precision floating-point number. 的本地化字符串。
        /// </summary>
        internal static string ToFloatDescription {
            get {
                return ResourceManager.GetString("ToFloatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToInt(Value)
        ///Converts Value to an equivalent 32-bit signed integer. 的本地化字符串。
        /// </summary>
        internal static string ToIntDescription {
            get {
                return ResourceManager.GetString("ToIntDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToLong(Value)
        ///Converts Value to an equivalent 64-bit signed integer. 的本地化字符串。
        /// </summary>
        internal static string ToLongDescription {
            get {
                return ResourceManager.GetString("ToLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToStr(Value)
        ///Returns a string representation of an object. 的本地化字符串。
        /// </summary>
        internal static string ToStrDescription {
            get {
                return ResourceManager.GetString("ToStrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trim(String)
        ///Removes all leading and trailing SPACE characters from String. 的本地化字符串。
        /// </summary>
        internal static string TrimDescription {
            get {
                return ResourceManager.GetString("TrimDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Represents the Boolean True value. 的本地化字符串。
        /// </summary>
        internal static string TrueDescription {
            get {
                return ResourceManager.GetString("TrueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression editor 的本地化字符串。
        /// </summary>
        internal static string UnboundColumnCaption {
            get {
                return ResourceManager.GetString("UnboundColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upper(String)
        ///Returns String in uppercase. 的本地化字符串。
        /// </summary>
        internal static string UpperDescription {
            get {
                return ResourceManager.GetString("UpperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UtcNow()
        ///Returns the current system date and time, expressed as Coordinated Universal Time (UTC). 的本地化字符串。
        /// </summary>
        internal static string UtcNowDescription {
            get {
                return ResourceManager.GetString("UtcNowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证数据表达式 的本地化字符串。
        /// </summary>
        internal static string ValidateDescription {
            get {
                return ResourceManager.GetString("ValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variables 的本地化字符串。
        /// </summary>
        internal static string VariablesText {
            get {
                return ResourceManager.GetString("VariablesText", resourceCulture);
            }
        }
    }
}
